spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql

  mail:
    host: smtp.gmail.com
    port: 587
    username: giftlistb66@gmail.com
    password: gbpeffsulwkgokwj
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
        transport:
          protocol: smtp

server:
  port: 1111

security:
  jwt:
    issuer: Nurgazy
    secret-word: veryveryveryveryverysecretword
    expires-at: 750

springdoc:
  api-docs:
    path: /swagger
